service: hh-transcription
plugins:
  - serverless-webpack
custom:
  webpack:
    includeModules: true
    packager: "npm"
    excludeFiles: src/**/*.test.js
provider:
  name: aws
  runtime: nodejs18.x
  timeout: 29
  versionFunctions: false
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  apiGateway:
    binaryMediaTypes:
      - "multipart/form-data"
  environment:
    TRANSCRIPTION_TABLE: ${self:service}-${self:provider.stage}-transcriptions
    AZURE_SPEECH_KEY: "your-azure-speech-key"
    AZURE_SPEECH_REGION: "your-azure-speech-region"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: "*"
  httpApi:
    id:
      "Fn::ImportValue": HH-HttpAPI-${sls:stage}
functions:
  createTranscription:
    handler: src/handlers/transcription.create
    events:
      - httpApi:
          path: /transcriptions
          method: post

  getTranscription:
    handler: src/handlers/transcription.get
    events:
      - httpApi:
          path: /transcriptions/{id}
          method: get

  updateTranscription:
    handler: src/handlers/transcription.update
    events:
      - httpApi:
          path: /transcriptions/{id}
          method: put

  deleteTranscription:
    handler: src/handlers/transcription.del
    events:
      - httpApi:
          path: /transcriptions/{id}
          method: delete

  listTranscriptions:
    handler: src/handlers/transcription.list
    events:
      - httpApi:
          path: /transcriptions
          method: get

  transcribeAudio:
    handler: src/handlers/transcription.transcribeAudio
    events:
      - httpApi:
          path: /transcriptions/transcribe
          method: post
    maximumPayloadSizeInMb: 10
resources:
  Resources:
    TranscriptionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TRANSCRIPTION_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: appointmentId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: AppointmentIdIndex
            KeySchema:
              - AttributeName: appointmentId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
